### ISSUE TITLE
Cat not connect MySQL clinet

### ISSUE THREAD

**Issue by ciusji** [Spotrix/spotrix#43]
Macos M1 mysqlclient Symbol not found: _mysql_affected_rows ERROR

**Comment by ciusji** [comment]
https://github.com/PyMySQL/mysqlclient/issues/496

**Comment by ciusji** [comment]
mkdir homebrew-x86 && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew-x86
arch -x86_64 homebrew-x86/bin/brew install mysql-client@5.7
git clone git@github.com:PyMySQL/mysqlclient.git
cd mysqlclient
export PATH=" /Users/admin/homebrew-x86/Cellar/mysql-client@5.7/5.7.34/bin:$PATH"
pip install mysqlclient

**Comment by ScottABrown** [comment]
Still yields `ImportError: dlopen(/Users/sbrown/.virtualenvs/llatitude/lib/python3.11/site-packages/MySQLdb/_mysql.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_mysql_affected_rows'`
